### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by r2evans** [jimhester/thank#6]
[You're right](https://twitter.com/jimhester_/status/1357680037470875649). So many jobs/tasks/repos only receive attention when something is needed.

![Thanks! You are da bomb!](https://media.giphy.com/media/eBqUy3ik6P2vK/giphy.gif)

Thanks @jimhester, I know you put a lot of honest effort and laser-focus into a lot of tools that I use every day (and take for granted).

![You rock](https://media1.giphy.com/media/cn355kwNmtyblxBjXQ/giphy.gif)

**Comment by jimhester** [comment]
![Thanks!](https://media.giphy.com/media/uj8YbXjNuwZ7iFRD4n/giphy.gif)
